# Generated by Django 4.1 on 2023-07-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issue',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publishing',
            field=models.IntegerField(default=2023),
        ),
    ]
